CREATE TABLE USUARIOPNP 
(
  IDUSUARIO NUMBER(*, 0) NOT NULL 
, APEPAT VARCHAR2(50 BYTE) 
, APEMAT VARCHAR2(50 BYTE) 
, NOMBRES VARCHAR2(50 BYTE) 
, ESTADO NUMBER(*, 0) 
, CIP VARCHAR2(8 BYTE) NOT NULL 
, PASSWORD VARCHAR2(20 BYTE) 
, FECHAREG DATE DEFAULT SYSDATE 
, USUMOD VARCHAR2(8 BYTE) 
, USUREG VARCHAR2(8 BYTE) 
, FECHAMOD DATE 
, CONSTRAINT USUARIOPNP_PK PRIMARY KEY 
  (
    IDUSUARIO 
  ));

ALTER TABLE USUARIOPNP
ADD CONSTRAINT USUARIOPNP_UK1 UNIQUE 
(
  CIP 
);

 CREATE SEQUENCE  "SEC_USUARIOPNP"  MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;